query ProjectIntroductions($id: ID!) {
  projectintroduction(id: $id) {
    id
    title
    content
    description
    keywords
    image_src
    image_new {
      url
    }
    published_at
    website
    explorer
    twitter
    telegram
    discord
    github
    genesis
    whitepaper
    ticker
    medium
    reddit
    facebook
    consensus_type
    algorithm
    block_time
    max_supply
    coinmarketcap
    coingecko
    asset_type
    roadmap
    team_members
    cmc_widget
  }
}
